---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      volumes:
      - name: pv0001-drupal-database
        persistentVolumeClaim:
          claimName: pv0001-drupal-database-claim
      - name: pv0001-drupal-modules
        persistentVolumeClaim:
          claimName: pv0001-drupal-modules-claim
      - name: pv0001-drupal-profiles
        persistentVolumeClaim:
          claimName: pv0001-drupal-profiles-claim
      - name: pv0001-drupal-themes
        persistentVolumeClaim:
          claimName: pv0001-drupal-themes-claim
      - name: pv0001-drupal-sites
        persistentVolumeClaim:
          claimName: pv0001-drupal-sites-claim
      containers:
      - name: drupal-database
        image: postgres:alpine3.15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DATABASE
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: pv0001-drupal-database
      - name: drupal
        image: drupal:9.2.17-php7.4-fpm-buster
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        volumeMounts:
          - mountPath: "/var/www/html/modules"
            name: pv0001-drupal-modules
          - mountPath: "/var/www/html/profiles"
            name: pv0001-drupal-profiles
          - mountPath: "/var/www/html/themes"
            name: pv0001-drupal-themes
          - mountPath: "/var/www/html/sites"
            name: pv0001-drupal-sites



        
          