---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      volumes:
      - name: pv0001-storage
        persistentVolumeClaim:
          claimName: pv0001-claim
      containers:
      - name: drupal-database
        image: postgres:alpine3.15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DATABASE
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: pv0001-storage
      - name: drupal
        image: postgres:alpine3.15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        
          