---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /web

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  volumeName: data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
